### ISSUE TITLE
NotSupportedError

### ISSUE THREAD

**Issue by aaisha79** [kov4l3nko/MEDUZA#1]
Hi when i try to run the following it keeps failing with the following:

python3 meduza.py -s com.xx.xxx.xxxxx unpinai.js 

Traceback (most recent call last):
  File "meduza.py", line 219, in <module>
    CertSpoofer()
  File "meduza.py", line 211, in __init__
    self.run_app()
  File "meduza.py", line 118, in run_app
    pid = self.device.spawn([self.app.identifier])
  File "/usr/local/lib/python3.8/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/frida/core.py", line 140, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.NotSupportedError: failed to get the task for process 5039

any help will be greatly appreciated..

Thanks

**Comment by kov4l3nko** [comment]
Please update Frida to the latest version on your device and mac and check:

1. If Frida can find the app:

    ```
    frida-ps -Uai
    ```

    Do you see your app in the list?

2. Try to spawn the app app with Frida:

   ```
   # Replace com.xx.xxx.xxxxx with your app identifier
   frida -U -f com.xx.xxx.xxxxx --no-pause
   ```

   What is the result?

**Comment by aaisha79** [comment]
Hey

So when i run:

_frida-ps -Uai_ i get a list of all the apps including the one i am trying to work with.

_frida -U -f com.xx.xxx.xxxxx --no-pause_ app launches and remains in foreground

**Comment by kov4l3nko** [comment]
Interesting... can you check one more thing for me? Please run the following code:

```python
# Write the code below to test.py, replace  com.xx.xxx.xxxxx with your app identifier, and run python3 test.py

import frida

device = frida.get_usb_device()
pid = device.spawn(["com.xx.xxx.xxxxx"])
```

Do you get any error?

**Comment by aaisha79** [comment]
So app runs however i get this error 

Traceback (most recent call last):
  File "test.py", line 4, in <module>
    pid = device.spawn(["com.xxx.xxx.xxxx"])
  File "/usr/local/lib/python3.8/site-packages/frida/core.py", line 26, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/frida/core.py", line 140, in spawn
    return self._impl.spawn(program, argv, envp, env, cwd, stdio, aux_options)
frida.NotSupportedError: failed to get the task for process 823

**Comment by kov4l3nko** [comment]
If the `test.py` does not work, your Frida Python bindings are probably broken. It does not related to MEDUZA itself, so it's hard to give you some silver bullet advice. To fix the error, I'd try

1. To install Frida with `pip` to a dedicated venv from scratch
2. To re-install Frida on your iOS device (remove it, the install again)
3. If 1-2 do not help, try other iOS device/mac (or PC)
4. If nothing helps, try to ask Frida devs for help, they track GitHub issues and (maybe) will help you

Sorry, this is all I can do for you at the moment 😞

**Comment by aaisha79** [comment]
thanks mate will give that a shot

**Comment by kov4l3nko** [comment]
@aaisha79 One more thing that could help... I don't know what the app you're trying to unpin, maybe the app implements some anti-Frida protection. Can you try `test.py` with an `com.apple.mobilemail`? (it does not implement any protection, for sure)

**Comment by aaisha79** [comment]
Hey Buddy

Thanks for that i am still getting the same message even with com.apple.mobilemail so it mist be something to do with my Frida setup i have tried uninstalling and reinstalling i have reached out here https://github.com/frida/frida-python waiting for a response.. can wait to try MEDUZA... Thanks

**Comment by aaisha79** [comment]
Resolved by installing FRIDA for Pre A12 devices as JB device in question was iphone 6
